package httpapi

// Two-factor authentication (TOTP, RFC 6238) for console login, and the
// single-use recovery codes that are its escape hatch. The persistence half
// — liveness, the atomic claims, the replay guard — is store/twofactor.go;
// the schema rationale is migrations/0016_two_factor.sql. This file owns the
// two things neither of those can: THE ALGORITHM, and the decision about what
// a presented code is worth.
//
// WHY THIS EXISTS. This console opens physical gates. A password is a single
// string that can be phished, reused from a breach, or read off a sticky
// note, and today it is the only thing between an attacker and a gate motor.
// A second factor makes a stolen password insufficient on its own.
//
// ============================================================================
// THE SECRET IS RECOVERABLE, AND CANNOT BE OTHERWISE
// ============================================================================
// Verifying a TOTP means the server recomputing HMAC-SHA1(secret, counter) and
// comparing. That requires the secret in plaintext. There is no hashing scheme
// that changes this; it is a property of the algorithm, not a shortcut.
//
// So the TOTP secret is the same class of value as the webhook signing key
// (webhooks.go) and the OPPOSITE class from a password (password.go) or a
// recovery-token verifier (authrecovery.go). It gets the signing key's
// discipline:
//
//	* generated by crypto/rand, 20 bytes / 160 bits (RFC 4226 §4 R6);
//	* handed to a client exactly ONCE, in the 201 body of
//	  POST /v1/auth/2fa/enroll, as the base32 string plus the otpauth:// URI
//	  a client renders as a QR code. There is no "show it again" endpoint and
//	  there cannot be one — losing it means disabling and re-enrolling;
//	* never in a listing projection: GET /v1/auth/2fa is served by
//	  store.TOTPStatus, whose SQL does not select the column at all;
//	* never logged, never in an error string, never in an audit detail.
//
// If you add a debug print of a secret here, you have written a
// gate-opening primitive that regenerates itself every thirty seconds.
//
// Stated plainly, because it bounds what this feature claims: anyone who can
// read the database file can mint valid codes for every enrolled user. 2FA
// here defends against a stolen PASSWORD, not against a stolen database.
//
// The RECOVERY CODES get the opposite treatment, because they are presented
// verbatim and compared — so they are hashed at rest, salted per row, and
// single-use. See "recovery codes" below.
//
// ============================================================================
// PARAMETERS, AND WHY EACH ONE
// ============================================================================
//	algorithm  HMAC-SHA1. RFC 6238's default and the only one Google
//	           Authenticator, Aegis, 1Password, Bitwarden and every other
//	           mainstream app accept without fuss. SHA-1's collision weakness
//	           is irrelevant to HMAC, which depends on PRF security; HMAC-SHA1
//	           remains unbroken (RFC 6194). Interoperability wins here, and it
//	           costs nothing real.
//	digits     6. The universal default. Eight would add ~6.6 bits, which is
//	           worth far less than the rate limit below is, at the price of an
//	           enrolment that half the apps display wrong.
//	period     30 seconds. RFC 6238's default X.
//	skew       ±1 step. See the next section — it is the one parameter here
//	           where "a bit more generous" is a real weakening.
//
// ============================================================================
// CLOCK SKEW: ±1 STEP, AND THE ARITHMETIC THAT PICKS IT
// ============================================================================
// A code is accepted from the current step, the one before, and the one
// after: THREE valid codes at any instant, a ~90 second acceptance window.
//
// RFC 6238 §5.2 names exactly this: validators SHOULD accept at most one time
// step of skew, and anything wider is a stated security tradeoff. One step
// absorbs the two real-world sources of drift — an NTP-synced phone against a
// self-hosted box whose own clock may be seconds off, and a human who reads a
// code at 29.5 seconds and finishes typing it at 31 — without paying for
// anything else.
//
// What "wider" would cost, concretely. Guessing a 6-digit code is 1 in 10^6
// per try; with a 3-code window it is 3 in 10^6. Each extra step either side
// adds two more valid codes, so ±2 is 5 in 10^6 — a 67% increase in an
// attacker's per-attempt odds, bought for drift that a correctly-configured
// clock does not have. It is not free, so it is not taken.
//
// FORWARD skew is symmetric with backward on purpose: the drift here is as
// likely to be the SERVER's (a self-hosted box that has been up for months
// without NTP) as the phone's. A future-step code, once spent, sets last_step
// forward — so the user's next code is refused until the clock catches up.
// That is a deliberate, visible thirty seconds of friction, not a hole.
//
// ============================================================================
// RATE LIMITING: THE THING THAT ACTUALLY MAKES SIX DIGITS ENOUGH
// ============================================================================
// A million possibilities is nothing against an unthrottled endpoint. Every
// verification path in this file — login, activation and disablement alike —
// shares ONE fixed-window failure counter, keyed on the USER ID, through the
// existing limiter (store.AuthAttemptsOverCap / RecordAuthFailure; see
// store/authratelimit.go for why the account-shaped limit counts only
// failures). No second mechanism was built.
//
// The counter is SHARED across the three endpoints deliberately: an attacker
// must not be able to refresh their guessing budget by switching from
// /login to /2fa/disable.
//
// totpVerifyPerWindow (5 per 5-minute window) is a CONSTANT, not an env var
// and not an instance_settings row — the same choice, for the same reason,
// that store/authratelimit.go makes for the other auth throttles: this is a
// security control, not a product quota, and an operator (or someone who has
// talked their way into the admin console) must not be able to quietly turn it
// down. Being a compile-time constant, it is stricter than those still are.
//
// THE RESIDUAL, STATED HONESTLY. 5 failures per 5 minutes is 1,440 guesses a
// day; at 3-in-10^6 that is roughly a 0.43% chance per day, so an attacker who
// ALREADY HAS THE PASSWORD and guesses flat out around the clock expects to
// succeed in about eight months — while generating 1,440 audited failures a
// day against one account. This is the ordinary posture of throttled TOTP and
// is why the second factor is a second factor and not a replacement for the
// first. A cumulative (NIST SP 800-63B style, ~100 total consecutive failures
// then lock) counter would close it properly; the existing limiter is
// fixed-window by design and building a second mechanism was out of scope.
// Recorded here rather than left for someone to rediscover.
//
// Keying on the user id, not on an attacker-supplied username, keeps this from
// becoming a lockout weapon: the counter is only ever reached AFTER a correct
// password, so a stranger cannot spend a victim's budget at all.
//
// ============================================================================
// ENROL → PROVE → ACTIVATE
// ============================================================================
// POST /v1/auth/2fa/enroll creates a PENDING factor. It gates nothing. Login
// is byte-for-byte unchanged while it exists. Only POST /v1/auth/2fa/activate,
// carrying a code that verifies, turns it on.
//
// The alternative — a secret that gates login the moment it is generated — is
// how you lock a user out of the hub that opens their own gates because a QR
// scan silently failed. See store.CreateTOTPEnrollment.
//
// ============================================================================
// RECOVERY CODES
// ============================================================================
// Ten codes, minted at ACTIVATION (never at enrolment — an abandoned
// enrolment must not leave live credentials behind), shown exactly once, in
// the activation response.
//
// Each is 16 characters of a 32-symbol alphabet = 80 bits of crypto/rand.
// Stored as hex(SHA-256(domain || salt || 0x00 || code)) against a fresh
// 128-bit per-row salt, compared with crypto/subtle.ConstantTimeCompare.
//
// A fast salted digest rather than argon2id, for the reason authrecovery.go
// gives at length: 80 bits of uniform randomness has no dictionary and no
// feasible offline search, so the slow KDF buys nothing — and verification
// must test a presented code against up to ten stored digests, which with
// argon2id would be ten memory-hard derivations per attempt and a denial of
// service handed to anyone who can reach the login endpoint. The salt is
// there to deny precomputation and cross-row correlation from a stolen
// database file.
//
// SINGLE USE, atomically, in the same transaction as the login it authorises
// — store.ClaimSecondFactorAndIssueRefresh. Never "verify then log in" as two
// statements.
//
// ============================================================================
// THE SOLE-ADMIN LOCKOUT QUESTION, ANSWERED RATHER THAN IMPLIED
// ============================================================================
// A sole instance admin who loses their authenticator must not be permanently
// locked out of the hub that opens their gates. Three things answer it, in
// order:
//
//  1. Nobody is forced into 2FA. It is opt-in per user; there is no instance
//     policy that mandates it, so an admin who never enrols is never at risk.
//  2. The ten recovery codes, shown once at activation, are the intended
//     answer, and GET /v1/auth/2fa reports how many remain so the count
//     cannot silently reach zero unnoticed. Any one of them logs the user in
//     AND is sufficient to disable 2FA outright.
//  3. If every code is also lost: this is a SELF-HOSTED hub. The operator has
//     the machine. `UPDATE user_totp SET disabled_at = unixepoch() WHERE
//     user_id = ...` against lintel.db, with the server stopped, restores
//     password-only login. That requires shell access to the box, which is a
//     strictly higher bar than the console login being protected — so it is a
//     legitimate last resort and not a bypass.
//
// Honest gap: (3) is a documented manual procedure, not a `gateway 2fa
// disable --user` subcommand. A supported command would be better than a hand
// -written UPDATE, and adding one to cmd/gateway is the obvious next step.
//
// Separately, and worth stating: losing console access does not lock anyone
// out of a BUILDING. Physical access does not route through this login —
// controllers hold their own keys, offline grants (offline_grants.go) are
// issued in advance precisely for the no-console case, and the chat channels
// authenticate against provider signatures, not against a session.

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha1"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base32"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/vul-os/aql/gateway/internal/store"
)

const (
	// See "PARAMETERS" in this file's doc comment for each of these.
	totpDigits    = 6
	totpPeriodS   = 30
	totpSkewSteps = 1
	// totpSecretBytes is 160 bits — RFC 4226 §4 R6's recommendation for an
	// HMAC-SHA1 key, and what every authenticator app expects.
	totpSecretBytes = 20
	// totpAlgorithm is what goes in the otpauth:// URI. Changing it here
	// without changing hotpCode below would provision apps with a secret this
	// server cannot verify.
	totpAlgorithm = "SHA1"
	// totpIssuer labels the entry in the user's authenticator app.
	totpIssuer = "Aql"

	// totpVerifyPerWindow is the shared failure budget for EVERY code
	// verification in this file, per user, per store.AuthWindowS. A constant,
	// not configuration — see this file's doc comment.
	totpVerifyPerWindow = 5
	// totpVerifyScope is the single rate-limit counter scope all three
	// verifying endpoints share, so switching endpoints does not buy a fresh
	// budget.
	totpVerifyScope = "totp_verify_acct"

	// Recovery codes: ten of them, 16 characters each from a 32-symbol
	// alphabet (80 bits), grouped in fours for transcription.
	recoveryCodeCount     = 10
	recoveryCodeChars     = 16
	recoveryCodeGroup     = 4
	totpRecoverySaltBytes = 16 // 128 bits, per row

	// recoveryCodeAlphabet is RFC 4648 base32's alphabet: 32 symbols, so a
	// random byte maps to one with no modulo bias, and no lowercase/digit
	// confusion (no 0/O, no 1/I/l) when a human copies one off paper.
	recoveryCodeAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"

	// totpRecoveryHashDomain separates these digests from every other SHA-256
	// in this codebase (recovery-token verifiers, API-token verifiers, the
	// audit chain), so no digest computed for one purpose can be replayed as a
	// valid value for another.
	totpRecoveryHashDomain = "aql/totp-recovery/v1/"
)

// b32 is the encoding for both the shared secret and the recovery-code
// alphabet: RFC 4648 base32, unpadded (authenticator apps reject '=').
var b32 = base32.StdEncoding.WithPadding(base32.NoPadding)

// ---------------------------------------------------------------------------
// RFC 4226 / RFC 6238
// ---------------------------------------------------------------------------

// hotpCode is RFC 4226 §5.3: HMAC-SHA1 over the 8-byte big-endian counter,
// dynamically truncated to a 31-bit integer, reduced mod 10^digits.
//
// This is the whole of the algorithm, in fourteen lines, using only the
// standard library. There is no dependency here and there does not need to be.
func hotpCode(secret []byte, counter uint64, digits int) string {
	var msg [8]byte
	binary.BigEndian.PutUint64(msg[:], counter)
	mac := hmac.New(sha1.New, secret)
	mac.Write(msg[:])
	sum := mac.Sum(nil)

	// Dynamic truncation: the low nibble of the last byte selects the offset.
	off := sum[len(sum)-1] & 0x0f
	// The high bit is masked off so the result is sign-agnostic across
	// implementations — RFC 4226 is explicit about this.
	bin := uint32(sum[off]&0x7f)<<24 |
		uint32(sum[off+1])<<16 |
		uint32(sum[off+2])<<8 |
		uint32(sum[off+3])

	mod := uint32(1)
	for i := 0; i < digits; i++ {
		mod *= 10
	}
	return fmt.Sprintf("%0*d", digits, bin%mod)
}

// totpCounter is RFC 6238's T = floor(unixTime / period). The Unix epoch is
// T0 = 0, the default.
func totpCounter(nowUnix int64, periodS int) int64 {
	return nowUnix / int64(periodS)
}

// verifyTOTP checks a presented code against every counter within skew of
// now, and reports which step matched.
//
// CONSTANT WORK ACROSS CANDIDATES: it never returns early on a match. Every
// candidate step is computed and compared on every call, and the match is
// accumulated, so the time taken does not reveal WHICH step matched (or that
// any did). The comparison itself is subtle.ConstantTimeCompare.
//
// The caller is still responsible for replay: this function reports the step,
// and only store.claimSecondFactorTx's guarded UPDATE decides whether that
// step may be spent. Check-then-act here would lose the race.
func verifyTOTP(secret []byte, digits, periodS, skew int, code string, nowUnix int64) (step int64, ok bool) {
	base := totpCounter(nowUnix, periodS)
	matched := 0
	var matchedStep int64
	for d := -skew; d <= skew; d++ {
		s := base + int64(d)
		if s < 0 {
			continue
		}
		want := hotpCode(secret, uint64(s), digits)
		eq := subtle.ConstantTimeCompare([]byte(want), []byte(code))
		// Branch-free accumulate: record the step on a match without a
		// conditional that would let the loop exit early.
		matchedStep = int64(subtle.ConstantTimeSelect(eq, int(s), int(matchedStep)))
		matched |= eq
	}
	return matchedStep, matched == 1
}

// normalizeTOTPCode accepts what a human actually types — "123 456", with
// stray whitespace — and rejects anything that is not exactly `digits` ASCII
// digits.
//
// This structural rejection happens BEFORE any HMAC is computed and is not a
// timing oracle: the length and character set of a valid code are public
// facts about RFC 6238, not facts about this user's secret.
func normalizeTOTPCode(raw string, digits int) (string, bool) {
	var b strings.Builder
	for _, r := range raw {
		switch {
		case r == ' ' || r == '-' || r == '\t':
			continue
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			return "", false
		}
	}
	s := b.String()
	if len(s) != digits {
		return "", false
	}
	return s, true
}

// newTOTPSecret returns a fresh base32 secret. An error from crypto/rand is
// fatal to the request — fail closed, never fall back to a weaker source.
func newTOTPSecret() (string, error) {
	b := make([]byte, totpSecretBytes)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return b32.EncodeToString(b), nil
}

// otpauthURI builds the standard provisioning URI a client renders as a QR
// code (the de-facto Key Uri Format). All parameters are stated explicitly
// rather than left to an app's defaults, so an app that defaults differently
// still provisions something this server can verify.
//
// The secret is IN this string. It is returned to the enrolling user once and
// must be treated exactly like the secret itself — never logged, never stored.
func otpauthURI(issuer, username, secretB32 string, digits, periodS int) string {
	q := url.Values{}
	q.Set("secret", secretB32)
	q.Set("issuer", issuer)
	q.Set("algorithm", totpAlgorithm)
	q.Set("digits", strconv.Itoa(digits))
	q.Set("period", strconv.Itoa(periodS))
	u := url.URL{
		Scheme:   "otpauth",
		Host:     "totp",
		Path:     "/" + issuer + ":" + username,
		RawQuery: q.Encode(),
	}
	return u.String()
}

// ---------------------------------------------------------------------------
// Recovery codes
// ---------------------------------------------------------------------------

// totpRecoveryHash is the one derivation both issuance and verification use.
func totpRecoveryHash(salt, code string) string {
	h := sha256.New()
	h.Write([]byte(totpRecoveryHashDomain))
	h.Write([]byte(salt))
	h.Write([]byte{0})
	h.Write([]byte(code))
	return hex.EncodeToString(h.Sum(nil))
}

// normalizeRecoveryCode makes transcription forgiving without making matching
// loose: case is folded up, and the grouping separators a human might or might
// not type are dropped. Everything else is preserved, so a wrong character is
// still a wrong code.
func normalizeRecoveryCode(raw string) string {
	var b strings.Builder
	for _, r := range strings.ToUpper(strings.TrimSpace(raw)) {
		if r == '-' || r == ' ' || r == '\t' {
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// newRecoveryCodes mints a batch: the plaintexts to show exactly once, and
// the salted digests to store. The two slices are parallel only in the sense
// that they were generated together — nothing links a stored row back to its
// plaintext, by construction.
func newRecoveryCodes() (plain []string, seeds []store.RecoveryCodeSeed, err error) {
	for i := 0; i < recoveryCodeCount; i++ {
		raw := make([]byte, recoveryCodeChars)
		if _, err := rand.Read(raw); err != nil {
			return nil, nil, err
		}
		var b strings.Builder
		for j, x := range raw {
			if j > 0 && j%recoveryCodeGroup == 0 {
				b.WriteByte('-')
			}
			// len(alphabet) is exactly 32, so &31 is an unbiased map from a
			// uniform byte. Do not change the alphabet length without
			// replacing this with rejection sampling.
			b.WriteByte(recoveryCodeAlphabet[x&31])
		}
		display := b.String()

		saltRaw := make([]byte, totpRecoverySaltBytes)
		if _, err := rand.Read(saltRaw); err != nil {
			return nil, nil, err
		}
		salt := hex.EncodeToString(saltRaw)
		plain = append(plain, display)
		seeds = append(seeds, store.RecoveryCodeSeed{
			Salt:     salt,
			CodeHash: totpRecoveryHash(salt, normalizeRecoveryCode(display)),
		})
	}
	return plain, seeds, nil
}

// dummyRecoveryCodeSalt keeps the "no codes left" and "wrong code" paths
// costing the same: matchRecoveryCode always performs at least one digest and
// one constant-time compare. Same technique handleLogin uses with dummyHash.
var dummyRecoveryCodeSalt = hex.EncodeToString(make([]byte, totpRecoverySaltBytes))

// matchRecoveryCode tests a presented code against every unspent row and
// returns the id of the one that matched.
//
// Like verifyTOTP, it does NOT return early: every row is hashed and compared
// on every call, so the time taken does not leak the position of the matching
// code (or the number of codes remaining). A match here is not authorisation —
// store.claimSecondFactorTx's guarded UPDATE is.
func matchRecoveryCode(rows []store.RecoveryCodeRow, presented string) (string, bool) {
	// Burn one comparison even with nothing to compare against.
	if len(rows) == 0 {
		_ = subtle.ConstantTimeCompare(
			[]byte(totpRecoveryHash(dummyRecoveryCodeSalt, presented)),
			[]byte(totpRecoveryHash(dummyRecoveryCodeSalt, "never-a-real-code")))
		return "", false
	}
	matched := 0
	matchedID := ""
	for _, row := range rows {
		got := totpRecoveryHash(row.Salt, presented)
		if subtle.ConstantTimeCompare([]byte(got), []byte(row.CodeHash)) == 1 {
			matched = 1
			matchedID = row.ID
		}
	}
	return matchedID, matched == 1
}

// ---------------------------------------------------------------------------
// Verification plumbing shared by login, activation and disablement
// ---------------------------------------------------------------------------

// twoFactorInput is the second-factor half of a request body. Exactly one of
// the two may be set; sending both is a structural error rather than a
// silently-preferred field, so a caller can never believe they proved
// something they did not.
type twoFactorInput struct {
	TOTPCode     string `json:"totp_code"`
	RecoveryCode string `json:"recovery_code"`
}

func (in twoFactorInput) empty() bool {
	return strings.TrimSpace(in.TOTPCode) == "" && strings.TrimSpace(in.RecoveryCode) == ""
}

func (in twoFactorInput) both() bool {
	return strings.TrimSpace(in.TOTPCode) != "" && strings.TrimSpace(in.RecoveryCode) != ""
}

// totpVerifyGate is the shared throttle in front of every code check. It
// writes the response itself on denial/error and returns false — the same
// shape as authIPGate.
//
// Fails CLOSED on a counter-store error, for the reason
// store/authratelimit.go gives: a brute-force gate that silently disables
// itself on a SQLite hiccup is worse than a briefly unavailable endpoint.
func (s *Server) totpVerifyGate(w http.ResponseWriter, r *http.Request, userID string) bool {
	over, retry, err := s.store.AuthAttemptsOverCap(r.Context(), totpVerifyScope, "user:"+userID,
		totpVerifyPerWindow, time.Now().Unix())
	if err != nil {
		s.log.Error("2fa rate limit check failed", "err", err)
		writeErr(w, http.StatusServiceUnavailable, "rate_limit_unavailable")
		return false
	}
	if over {
		w.Header().Set("Retry-After", strconv.FormatInt(retry, 10))
		writeErr(w, http.StatusTooManyRequests, "rate_limited")
		return false
	}
	return true
}

// recordTOTPFailure spends one unit of the shared budget. Called ONLY after a
// verification actually failed — never on a merely absent code, which is the
// normal first leg of a two-step login and must not cost a user their budget.
func (s *Server) recordTOTPFailure(ctx context.Context, userID string) {
	if err := s.store.RecordAuthFailure(ctx, totpVerifyScope, "user:"+userID, time.Now().Unix()); err != nil {
		s.log.Error("record 2fa failure", "err", err)
	}
}

// verifySecondFactor turns a presented credential into an unspent claim, or
// reports one indistinguishable failure. It does not spend anything — see
// store.SecondFactorClaim.
//
// The factor's OWN digits/period are used, not the current package defaults,
// so an enrolment provisioned under different parameters keeps working.
func (s *Server) verifySecondFactor(ctx context.Context, f *store.TOTPFactor, in twoFactorInput) (store.SecondFactorClaim, bool) {
	if strings.TrimSpace(in.RecoveryCode) != "" {
		rows, err := s.store.LiveRecoveryCodes(ctx, f.ID)
		if err != nil {
			s.log.Error("load recovery codes", "err", err)
			return store.SecondFactorClaim{}, false
		}
		id, ok := matchRecoveryCode(rows, normalizeRecoveryCode(in.RecoveryCode))
		if !ok {
			return store.SecondFactorClaim{}, false
		}
		return store.SecondFactorClaim{
			Kind: store.SecondFactorRecoveryCode, FactorID: f.ID, CodeID: id,
		}, true
	}

	code, wellFormed := normalizeTOTPCode(in.TOTPCode, f.Digits)
	if !wellFormed {
		return store.SecondFactorClaim{}, false
	}
	secret, err := b32.DecodeString(f.Secret)
	if err != nil {
		// A secret that will not decode is a corrupt row, not a user error.
		// Fail closed and say nothing about it to the caller.
		s.log.Error("totp secret decode failed", "factor_id", f.ID)
		return store.SecondFactorClaim{}, false
	}
	step, ok := verifyTOTP(secret, f.Digits, f.PeriodS, totpSkewSteps, code, time.Now().Unix())
	if !ok {
		return store.SecondFactorClaim{}, false
	}
	// Early replay check: a code from a step already spent is refused here so
	// the caller gets the ordinary "wrong code" answer. This is an early-out
	// only — the authority is the guarded UPDATE in the store, which is what
	// actually wins the concurrent-replay race.
	if f.LastStep.Valid && step <= f.LastStep.Int64 {
		return store.SecondFactorClaim{}, false
	}
	return store.SecondFactorClaim{Kind: store.SecondFactorTOTP, FactorID: f.ID, Step: step}, true
}

// ---------------------------------------------------------------------------
// The login gate (called from auth.go's handleLogin)
// ---------------------------------------------------------------------------

// secondFactorGate runs after the password has verified and decides whether a
// session may be issued. It returns (nil, true) — no claim, proceed — for the
// overwhelmingly common case of a user with no ACTIVE factor, which is what
// keeps login byte-for-byte unchanged for everyone who has not enrolled.
//
// It writes the response itself on refusal and returns false.
//
// FAILS CLOSED. If the factor lookup errors, we cannot tell whether 2FA is on,
// so no session is issued. A read error must never degrade into
// password-only login.
func (s *Server) secondFactorGate(w http.ResponseWriter, r *http.Request, u *store.User, in twoFactorInput) (*store.SecondFactorClaim, bool) {
	f, err := s.store.LiveTOTPFactor(r.Context(), u.ID)
	if errors.Is(err, store.ErrNotFound) {
		return nil, true
	}
	if err != nil {
		s.log.Error("live totp lookup", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return nil, false
	}
	if !f.Active() {
		// Pending enrolment: gates nothing. See "ENROL → PROVE → ACTIVATE".
		return nil, true
	}
	if in.both() {
		writeErr(w, http.StatusBadRequest, "conflicting_second_factor")
		return nil, false
	}
	if in.empty() {
		// Not a failure — the client now knows to ask for a code and retry
		// with the password. Deliberately does NOT spend rate-limit budget.
		//
		// There is no intermediate "half-authenticated" token here on
		// purpose: the password is presented again with the code, so there is
		// no short-lived credential to steal, replay, or forget to expire.
		writeErr(w, http.StatusUnauthorized, "totp_required")
		return nil, false
	}
	if !s.totpVerifyGate(w, r, u.ID) {
		return nil, false
	}
	claim, ok := s.verifySecondFactor(r.Context(), f, in)
	if !ok {
		s.recordTOTPFailure(r.Context(), u.ID)
		if err := s.store.WriteAdminAudit(r.Context(), u.ID, "2fa_login", "user", u.ID, false,
			map[string]any{"reason": "invalid_second_factor"}); err != nil {
			s.log.Error("audit 2fa_login", "err", err)
		}
		// One refusal for every cause — wrong code, replayed code, expired
		// step, unknown recovery code, already-spent recovery code.
		writeErr(w, http.StatusUnauthorized, "invalid_second_factor")
		return nil, false
	}
	return &claim, true
}

// issueTokensClaimed issues access+refresh, spending a second-factor claim in
// the SAME transaction as the refresh-token insert when one is present.
//
// A nil claim is the no-2FA path and behaves exactly like the original
// issueTokensCtx: one unconditional insert. This is the single funnel both
// paths go through, so there is no way to add a login route that quietly skips
// the claim.
func (s *Server) issueTokensClaimed(w http.ResponseWriter, r *http.Request, u *store.User, claim *store.SecondFactorClaim) (map[string]any, bool) {
	access, err := SignJWT(s.cfg.JWTSecret, u.ID, u.Username, u.IsPlatformAdmin, accessTTL)
	if err != nil {
		writeErr(w, http.StatusInternalServerError, "internal")
		return nil, false
	}
	refresh := randomToken()
	expiresAt := time.Now().Add(refreshTTL).Unix()

	if claim == nil {
		if err := s.store.InsertRefreshToken(r.Context(), store.NewID(), store.NewID(), u.ID,
			hashToken(refresh), expiresAt); err != nil {
			writeErr(w, http.StatusInternalServerError, "internal")
			return nil, false
		}
		return map[string]any{"access_token": access, "refresh_token": refresh}, true
	}

	err = s.store.ClaimSecondFactorAndIssueRefresh(r.Context(), u.ID, *claim,
		store.NewID(), store.NewID(), hashToken(refresh), expiresAt)
	if errors.Is(err, store.ErrTOTPUnusable) {
		// Lost the replay/double-spend race between verification and claim.
		// Same refusal a wrong code gets, and no session exists.
		s.recordTOTPFailure(r.Context(), u.ID)
		writeErr(w, http.StatusUnauthorized, "invalid_second_factor")
		return nil, false
	}
	if err != nil {
		s.log.Error("claim second factor", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return nil, false
	}
	if err := s.store.WriteAdminAudit(r.Context(), u.ID, "2fa_login", "user", u.ID, true,
		map[string]any{"method": string(claim.Kind)}); err != nil {
		s.log.Error("audit 2fa_login", "err", err)
	}
	return map[string]any{"access_token": access, "refresh_token": refresh}, true
}

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

// GET /v1/auth/2fa — status for the caller. Served by store.TOTPStatus, whose
// SQL does not select the secret column, so this response shape cannot carry
// it even by accident.
func (s *Server) handleTwoFactorStatus(w http.ResponseWriter, r *http.Request) {
	c := claimsFrom(r)
	st, err := s.store.TOTPStatus(r.Context(), c.Sub)
	if err != nil {
		s.log.Error("totp status", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"enrolled":     st.Enrolled,
		"active":       st.Active,
		"pending":      st.Pending,
		"created_at":   st.CreatedAt,
		"activated_at": nullInt64(st.ActivatedAt),
		// Surfaced so a user cannot silently reach zero — see the sole-admin
		// lockout note in this file's doc comment.
		"recovery_codes_remaining": st.RecoveryCodesRemaining,
		"algorithm":                totpAlgorithm,
		"digits":                   totpDigits,
		"period_seconds":           totpPeriodS,
	})
}

// POST /v1/auth/2fa/enroll — begin enrolment.
//
// Returns the secret and the otpauth:// URI ONCE. Nothing gates login yet:
// the factor is pending until POST /v1/auth/2fa/activate proves possession.
//
// Throttled on the register (issuance) budget rather than the login one, the
// same call authrecovery.go's forgot-password makes: this endpoint writes a
// row, it does not check a credential.
func (s *Server) handleTwoFactorEnroll(w http.ResponseWriter, r *http.Request) {
	if !s.authIPGate(w, r, "totp_enroll_ip", s.cfg.AuthRateLimits.RegisterIPPerWindow) {
		return
	}
	c := claimsFrom(r)
	u, err := s.store.UserByID(r.Context(), c.Sub)
	if err != nil {
		writeErr(w, http.StatusUnauthorized, "unauthorized")
		return
	}
	secret, err := newTOTPSecret()
	if err != nil {
		s.log.Error("totp secret generation failed", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return
	}
	f, err := s.store.CreateTOTPEnrollment(r.Context(), u.ID, secret, totpDigits, totpPeriodS)
	if errors.Is(err, store.ErrTOTPAlreadyActive) {
		// Deliberate: re-enrolling over a live factor would be a way for a
		// stolen session to swap the second factor without proving anything.
		writeErr(w, http.StatusConflict, "totp_already_active")
		return
	}
	if err != nil {
		s.log.Error("totp enroll", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return
	}
	// Audited — but the detail names only the factor, never the secret.
	if err := s.store.WriteAdminAudit(r.Context(), u.ID, "2fa_enroll_start", "user", u.ID, true,
		map[string]any{"factor_id": f.ID}); err != nil {
		s.log.Error("audit 2fa_enroll_start", "err", err)
	}
	// The ONE moment the secret is visible. There is no second one.
	writeJSON(w, http.StatusCreated, map[string]any{
		"secret":            secret,
		"otpauth_uri":       otpauthURI(totpIssuer, u.Username, secret, totpDigits, totpPeriodS),
		"algorithm":         totpAlgorithm,
		"digits":            totpDigits,
		"period_seconds":    totpPeriodS,
		"secret_shown_once": true,
		"pending":           true,
	})
}

// DELETE /v1/auth/2fa/enroll — abandon an unproven enrolment.
//
// Refuses to touch an ACTIVE factor: turning real 2FA off is the disable
// route's job and requires proving possession. This exists only so "I closed
// the tab halfway through" is not a state a user must prove their way out of.
func (s *Server) handleTwoFactorEnrollCancel(w http.ResponseWriter, r *http.Request) {
	c := claimsFrom(r)
	f, err := s.store.LiveTOTPFactor(r.Context(), c.Sub)
	if errors.Is(err, store.ErrNotFound) {
		writeErr(w, http.StatusNotFound, "no_pending_enrollment")
		return
	}
	if err != nil {
		s.log.Error("live totp lookup", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return
	}
	if err := s.store.CancelPendingTOTP(r.Context(), f.ID, c.Sub); err != nil {
		// ErrTOTPUnusable here means the factor is active — the honest answer
		// is "there is no pending enrolment to cancel", not a 500.
		writeErr(w, http.StatusNotFound, "no_pending_enrollment")
		return
	}
	if err := s.store.WriteAdminAudit(r.Context(), c.Sub, "2fa_enroll_cancel", "user", c.Sub, true,
		map[string]any{"factor_id": f.ID}); err != nil {
		s.log.Error("audit 2fa_enroll_cancel", "err", err)
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

type twoFactorActivateReq struct {
	TOTPCode string `json:"totp_code"`
}

// POST /v1/auth/2fa/activate — prove possession and turn 2FA on.
//
// The proving code, the activation and the recovery-code batch all land in
// ONE transaction (store.ActivateTOTP): 2FA is never on without an escape
// hatch, and the proving code's counter is spent so it cannot be immediately
// replayed as a login.
//
// The recovery codes are in the response body. That is the only time they
// exist outside a salted digest.
func (s *Server) handleTwoFactorActivate(w http.ResponseWriter, r *http.Request) {
	if !s.authIPGate(w, r, "totp_activate_ip", s.cfg.AuthRateLimits.LoginIPPerWindow) {
		return
	}
	c := claimsFrom(r)
	var req twoFactorActivateReq
	if !readJSON(w, r, &req) {
		return
	}
	f, err := s.store.LiveTOTPFactor(r.Context(), c.Sub)
	if errors.Is(err, store.ErrNotFound) {
		writeErr(w, http.StatusConflict, "no_pending_enrollment")
		return
	}
	if err != nil {
		s.log.Error("live totp lookup", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return
	}
	if !f.Pending() {
		writeErr(w, http.StatusConflict, "no_pending_enrollment")
		return
	}
	if !s.totpVerifyGate(w, r, c.Sub) {
		return
	}
	// Activation accepts an authenticator code only. A recovery code cannot
	// activate a factor: none exist yet, and accepting the field here would
	// invite a caller to believe otherwise.
	claim, ok := s.verifySecondFactor(r.Context(), f, twoFactorInput{TOTPCode: req.TOTPCode})
	if !ok || claim.Kind != store.SecondFactorTOTP {
		s.recordTOTPFailure(r.Context(), c.Sub)
		writeErr(w, http.StatusUnauthorized, "invalid_second_factor")
		return
	}
	plain, seeds, err := newRecoveryCodes()
	if err != nil {
		s.log.Error("recovery code generation failed", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return
	}
	if err := s.store.ActivateTOTP(r.Context(), f.ID, c.Sub, claim.Step, seeds); err != nil {
		if errors.Is(err, store.ErrTOTPUnusable) {
			writeErr(w, http.StatusConflict, "no_pending_enrollment")
			return
		}
		s.log.Error("totp activate", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return
	}
	if err := s.store.WriteAdminAudit(r.Context(), c.Sub, "2fa_activate", "user", c.Sub, true,
		map[string]any{"factor_id": f.ID, "recovery_codes": len(plain)}); err != nil {
		s.log.Error("audit 2fa_activate", "err", err)
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"active":                    true,
		"recovery_codes":            plain,
		"recovery_codes_shown_once": true,
	})
}

// POST /v1/auth/2fa/disable — turn 2FA off, and prove possession to do it.
//
// A current authenticator code or an unspent recovery code is REQUIRED. A
// live session is not enough, and that is the entire point: the second factor
// exists to survive a stolen session, so a stolen session must not be able to
// remove it. Whichever credential is presented is SPENT in the same
// transaction as the teardown, so it cannot be replayed afterwards.
func (s *Server) handleTwoFactorDisable(w http.ResponseWriter, r *http.Request) {
	if !s.authIPGate(w, r, "totp_disable_ip", s.cfg.AuthRateLimits.LoginIPPerWindow) {
		return
	}
	c := claimsFrom(r)
	var in twoFactorInput
	if !readJSON(w, r, &in) {
		return
	}
	if in.both() {
		writeErr(w, http.StatusBadRequest, "conflicting_second_factor")
		return
	}
	if in.empty() {
		// The refusal this route exists for. Never a 200.
		writeErr(w, http.StatusBadRequest, "second_factor_required")
		return
	}
	f, err := s.store.LiveTOTPFactor(r.Context(), c.Sub)
	if errors.Is(err, store.ErrNotFound) {
		writeErr(w, http.StatusConflict, "totp_not_active")
		return
	}
	if err != nil {
		s.log.Error("live totp lookup", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return
	}
	if !f.Active() {
		writeErr(w, http.StatusConflict, "totp_not_active")
		return
	}
	if !s.totpVerifyGate(w, r, c.Sub) {
		return
	}
	claim, ok := s.verifySecondFactor(r.Context(), f, in)
	if !ok {
		s.recordTOTPFailure(r.Context(), c.Sub)
		if err := s.store.WriteAdminAudit(r.Context(), c.Sub, "2fa_disable", "user", c.Sub, false,
			map[string]any{"reason": "invalid_second_factor"}); err != nil {
			s.log.Error("audit 2fa_disable", "err", err)
		}
		writeErr(w, http.StatusUnauthorized, "invalid_second_factor")
		return
	}
	if err := s.store.DisableTOTP(r.Context(), c.Sub, claim); err != nil {
		if errors.Is(err, store.ErrTOTPUnusable) {
			s.recordTOTPFailure(r.Context(), c.Sub)
			writeErr(w, http.StatusUnauthorized, "invalid_second_factor")
			return
		}
		s.log.Error("totp disable", "err", err)
		writeErr(w, http.StatusInternalServerError, "internal")
		return
	}
	if err := s.store.WriteAdminAudit(r.Context(), c.Sub, "2fa_disable", "user", c.Sub, true,
		map[string]any{"factor_id": f.ID, "method": string(claim.Kind)}); err != nil {
		s.log.Error("audit 2fa_disable", "err", err)
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "active": false})
}
