package camera

import (
	"bytes"
	"encoding/binary"
	"testing"
)

// RFC 6184 depacketization, tested against literal bytes rather than against
// this package's own output.
//
// The trap named in h264.go's file comment and in this repository's own
// history is round-tripping a depacketizer against a packetizer written in
// the same package: that proves the two agree with each other, and proves
// nothing about whether either agrees with RFC 6184. So every vector below is
// a byte slice written by hand from the RFC's field layouts (§5.3 NAL header,
// §5.7.1 STAP-A, §5.8 FU-A), with the bit layout spelled out in a comment next
// to it — checkable against the RFC by eye, not generated by calling into
// this file's own encoder because this file has no encoder.

// buildRTP wraps an H.264 payload in the fixed 12-byte RTP header (RFC 3550
// §5.1). Byte 0 is always 0x80: version=2 (bits 7-6 = 10), padding=0,
// extension=0, CSRC count=0000. Byte 1 (marker + payload type) and the
// timestamp/SSRC words are left zero because Push never looks at them — only
// the sequence number at bytes 2-3 matters to the code under test here.
func buildRTP(seq uint16, payload []byte) []byte {
	pkt := make([]byte, 12+len(payload))
	pkt[0] = 0x80
	pkt[1] = 96 // an arbitrary dynamic payload type
	binary.BigEndian.PutUint16(pkt[2:4], seq)
	copy(pkt[12:], payload)
	return pkt
}

func annexBOf(nal []byte) []byte {
	return append([]byte{0, 0, 0, 1}, nal...)
}

// ── single NAL unit packets (RFC 6184 §5.6, types 1-23) ─────────────────────

func TestSingleNALUnitPacketIsPassedThroughWithAStartCode(t *testing.T) {
	// A single NAL unit packet's RTP payload IS the NAL unit: header byte
	// then RBSP. 0x67 is F=0, NRI=11 (bits 6-5), Type=00111=7 (SPS) — a byte
	// value real H.264 SPS NAL units in the wild actually start with.
	payload := []byte{0x67, 0x42, 0x00, 0x1e, 0xab, 0xcd}
	d := NewDepacketizer()
	nals, err := d.Push(buildRTP(1000, payload))
	if err != nil {
		t.Fatalf("Push: %v", err)
	}
	if len(nals) != 1 {
		t.Fatalf("got %d NALs, want 1", len(nals))
	}
	if want := annexBOf(payload); !bytes.Equal(nals[0], want) {
		t.Errorf("NAL = % x, want % x", nals[0], want)
	}
	if d.Emitted() != 1 || d.Dropped() != 0 {
		t.Errorf("emitted=%d dropped=%d, want 1/0", d.Emitted(), d.Dropped())
	}
}

// ── STAP-A aggregation (RFC 6184 §5.7.1, type 24) ────────────────────────────

func TestSTAPAAggregatesTwoNALs(t *testing.T) {
	// STAP-A header byte: F=0, NRI=00, Type=11000=24 -> 0x18.
	// Then, twice: a big-endian uint16 size followed by exactly that many
	// bytes of one complete NAL unit (header included).
	//
	//   NAL A: 0x68 0xCE            (PPS: F=0 NRI=01 Type=01000=8, 2 bytes)
	//   NAL B: 0x65 0x88 0x84       (IDR slice: F=0 NRI=10 Type=00101=5, 3 bytes)
	nalA := []byte{0x68, 0xCE}
	nalB := []byte{0x65, 0x88, 0x84}
	payload := []byte{0x18}
	payload = append(payload, 0x00, 0x02)
	payload = append(payload, nalA...)
	payload = append(payload, 0x00, 0x03)
	payload = append(payload, nalB...)

	d := NewDepacketizer()
	nals, err := d.Push(buildRTP(2000, payload))
	if err != nil {
		t.Fatalf("Push: %v", err)
	}
	if len(nals) != 2 {
		t.Fatalf("got %d NALs, want 2", len(nals))
	}
	if !bytes.Equal(nals[0], annexBOf(nalA)) {
		t.Errorf("NAL[0] = % x, want % x", nals[0], annexBOf(nalA))
	}
	if !bytes.Equal(nals[1], annexBOf(nalB)) {
		t.Errorf("NAL[1] = % x, want % x", nals[1], annexBOf(nalB))
	}
	if d.Emitted() != 2 || d.Dropped() != 0 {
		t.Errorf("emitted=%d dropped=%d, want 2/0", d.Emitted(), d.Dropped())
	}
}

// A truncated STAP-A whose declared inner size runs past what the packet
// actually carries must not panic, must not fabricate a NAL from bytes that
// are not there, and must still return whatever NAL units it already fully
// validated before the truncation.
func TestSTAPATruncatedSizeIsBoundsChecked(t *testing.T) {
	t.Run("size field claims more than remains", func(t *testing.T) {
		// Header 0x18, then a size of 5 with only 2 bytes actually following.
		payload := []byte{0x18, 0x00, 0x05, 0xAA, 0xBB}
		d := NewDepacketizer()
		nals, err := d.Push(buildRTP(1, payload))
		if err == nil {
			t.Fatal("want an error for a STAP-A whose size overruns the packet")
		}
		if len(nals) != 0 {
			t.Fatalf("got %d NALs from a wholly-truncated STAP-A, want 0", len(nals))
		}
		if d.Dropped() != 1 {
			t.Errorf("Dropped() = %d, want 1", d.Dropped())
		}
	})

	t.Run("first entry valid, second truncated", func(t *testing.T) {
		nalA := []byte{0xAA, 0xBB}
		payload := []byte{0x18, 0x00, 0x02}
		payload = append(payload, nalA...)
		// Second entry claims size 5 but only 1 byte remains.
		payload = append(payload, 0x00, 0x05, 0xCC)
		d := NewDepacketizer()
		nals, err := d.Push(buildRTP(2, payload))
		if err == nil {
			t.Fatal("want an error for the truncated second entry")
		}
		if len(nals) != 1 || !bytes.Equal(nals[0], annexBOf(nalA)) {
			t.Fatalf("got %v, want exactly the one valid NAL that preceded the truncation", nals)
		}
		if d.Dropped() != 1 {
			t.Errorf("Dropped() = %d, want 1 (the entry that could not be recovered)", d.Dropped())
		}
	})

	t.Run("size field itself runs past the packet", func(t *testing.T) {
		// Header 0x18, then a single byte where a 2-byte size field was
		// promised.
		payload := []byte{0x18, 0x00}
		d := NewDepacketizer()
		nals, err := d.Push(buildRTP(3, payload))
		if err == nil {
			t.Fatal("want an error, not a panic or a fabricated NAL")
		}
		if len(nals) != 0 {
			t.Fatalf("got %d NALs, want 0", len(nals))
		}
	})
}

// ── FU-A fragmentation (RFC 6184 §5.8, type 28) ──────────────────────────────

// The reconstructed NAL header must come from TWO different bytes across the
// fragments, not from either alone: F/NRI from the FU indicator, Type from
// the FU header. Traced out here so the expected value is checkable by eye
// against RFC 6184 §5.8 rather than only against the code that computes it.
func TestFUAReassemblesAcrossThreeFragments(t *testing.T) {
	// Original (never-sent-whole) NAL header: F=0, NRI=10, Type=00101=5 (IDR
	// slice) -> 0b01000101 = 0x45.
	//
	// FU indicator (byte 0 of every fragment): F=0, NRI=10 (carried through
	// from the original), Type=11100=28 -> 0b01011100 = 0x5C.
	const fuIndicator = 0x5C
	// FU header (byte 1 of every fragment): S | E | R(=0) | Type(5, the
	// ORIGINAL nal_unit_type=5=00101).
	const fuHeaderStart = 0x85 // 1 0 0 00101 — S=1, E=0
	const fuHeaderMid = 0x05   // 0 0 0 00101 — S=0, E=0
	const fuHeaderEnd = 0x45   // 0 1 0 00101 — S=0, E=1

	start := []byte{fuIndicator, fuHeaderStart, 0xAA, 0xBB}
	mid := []byte{fuIndicator, fuHeaderMid, 0xCC, 0xDD}
	end := []byte{fuIndicator, fuHeaderEnd, 0xEE}

	d := NewDepacketizer()

	if nals, err := d.Push(buildRTP(10, start)); err != nil || len(nals) != 0 {
		t.Fatalf("start fragment: nals=%v err=%v, want none yet", nals, err)
	}
	if nals, err := d.Push(buildRTP(11, mid)); err != nil || len(nals) != 0 {
		t.Fatalf("middle fragment: nals=%v err=%v, want none yet", nals, err)
	}
	nals, err := d.Push(buildRTP(12, end))
	if err != nil {
		t.Fatalf("end fragment: %v", err)
	}
	if len(nals) != 1 {
		t.Fatalf("got %d NALs on the end fragment, want 1", len(nals))
	}

	// Reconstructed header 0x45, exactly as traced in the comment above,
	// followed by every fragment's payload bytes in order.
	want := annexBOf([]byte{0x45, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE})
	if !bytes.Equal(nals[0], want) {
		t.Errorf("reassembled NAL = % x, want % x", nals[0], want)
	}
	if d.Emitted() != 1 || d.Dropped() != 0 {
		t.Errorf("emitted=%d dropped=%d, want 1/0", d.Emitted(), d.Dropped())
	}
}

// RFC 6184 §5.8 permits S and E both set on a single fragment: a
// "fragmentation unit" of exactly one fragment. Unusual, not invalid.
func TestFUASingleFragmentWithStartAndEndBothSet(t *testing.T) {
	const fuIndicator = 0x5C  // same F/NRI as above
	const fuHeaderBoth = 0xC5 // S=1 E=1 R=0 Type=00101 -> 1 1 0 00101
	pkt := buildRTP(50, []byte{fuIndicator, fuHeaderBoth, 0x11, 0x22})

	d := NewDepacketizer()
	nals, err := d.Push(pkt)
	if err != nil {
		t.Fatalf("Push: %v", err)
	}
	want := annexBOf([]byte{0x45, 0x11, 0x22})
	if len(nals) != 1 || !bytes.Equal(nals[0], want) {
		t.Fatalf("got %v, want [%x]", nals, want)
	}
}

// A lost packet mid-FU-A must discard the partial NAL — never emit it
// half-formed, and never let the E bit on a later, gap-separated packet be
// mistaken for the same reassembly's true end.
func TestFUALostMiddleFragmentDiscardsPartialNAL(t *testing.T) {
	const fuIndicator = 0x5C
	const fuHeaderStart = 0x85
	const fuHeaderEnd = 0x45

	start := []byte{fuIndicator, fuHeaderStart, 0xAA, 0xBB}
	// The middle fragment (would have been seq 21) never arrives.
	end := []byte{fuIndicator, fuHeaderEnd, 0xEE}

	d := NewDepacketizer()
	if nals, err := d.Push(buildRTP(20, start)); err != nil || len(nals) != 0 {
		t.Fatalf("start: nals=%v err=%v", nals, err)
	}
	nals, err := d.Push(buildRTP(22, end)) // seq jumped 20 -> 22, skipping 21
	if err == nil {
		t.Fatal("want an error reporting the sequence gap")
	}
	if len(nals) != 0 {
		t.Fatalf("got %d NALs from a gapped reassembly, want 0 — a partial NAL must never be emitted", len(nals))
	}
	if d.Emitted() != 0 {
		t.Errorf("Emitted() = %d, want 0", d.Emitted())
	}
	if d.Dropped() != 1 {
		t.Errorf("Dropped() = %d, want 1", d.Dropped())
	}

	// The assembler must recover for the NEXT NAL rather than staying wedged.
	start2 := []byte{fuIndicator, fuHeaderStart, 0x01}
	end2 := []byte{fuIndicator, fuHeaderEnd, 0x02}
	if nals, err := d.Push(buildRTP(30, start2)); err != nil || len(nals) != 0 {
		t.Fatalf("post-recovery start: nals=%v err=%v", nals, err)
	}
	nals, err = d.Push(buildRTP(31, end2))
	if err != nil {
		t.Fatalf("post-recovery end: %v", err)
	}
	want := annexBOf([]byte{0x45, 0x01, 0x02})
	if len(nals) != 1 || !bytes.Equal(nals[0], want) {
		t.Fatalf("recovered NAL = %v, want [%x]", nals, want)
	}
	if d.Dropped() != 1 {
		t.Errorf("Dropped() after recovery = %d, want still 1 (unchanged)", d.Dropped())
	}
}

// An FU-A whose start bit was never seen must be dropped, not treated as a
// start: there is no FU indicator/header pair from a genuine S=1 packet to
// rebuild the original NAL header from, so anything built from just a
// continuation fragment would have a fabricated header.
func TestFUAContinuationWithNoStartIsDropped(t *testing.T) {
	const fuIndicator = 0x5C
	const fuHeaderMid = 0x05

	d := NewDepacketizer()
	// The very first fragment this Depacketizer ever sees is a continuation.
	nals, err := d.Push(buildRTP(100, []byte{fuIndicator, fuHeaderMid, 0xCC}))
	if err == nil {
		t.Fatal("want an error for a continuation with no start")
	}
	if len(nals) != 0 {
		t.Fatalf("got %d NALs, want 0", len(nals))
	}
	if d.Dropped() != 1 {
		t.Errorf("Dropped() = %d, want 1", d.Dropped())
	}

	// A subsequent, properly-started run must still work — the missing
	// start must not wedge the assembler permanently.
	const fuHeaderStart = 0x85
	const fuHeaderEnd = 0x45
	if nals, err := d.Push(buildRTP(101, []byte{fuIndicator, fuHeaderStart, 0x01})); err != nil || len(nals) != 0 {
		t.Fatalf("start: nals=%v err=%v", nals, err)
	}
	nals, err = d.Push(buildRTP(102, []byte{fuIndicator, fuHeaderEnd, 0x02}))
	if err != nil {
		t.Fatalf("end: %v", err)
	}
	want := annexBOf([]byte{0x45, 0x01, 0x02})
	if len(nals) != 1 || !bytes.Equal(nals[0], want) {
		t.Fatalf("got %v, want [%x]", nals, want)
	}
}

// Out-of-order arrival: the network reorders two of an FU-A run's fragments
// in flight, so this Depacketizer sees them in the wrong order. It must never
// glue mismatched fragments into something that claims to be a complete NAL.
func TestFUAOutOfOrderArrivalNeverEmitsFalseComplete(t *testing.T) {
	const fuIndicator = 0x5C
	const fuHeaderStart = 0x85
	const fuHeaderMid = 0x05
	const fuHeaderEnd = 0x45

	d := NewDepacketizer()
	// Sent as seq 200 (start), 201 (middle), 202 (end); DELIVERED as
	// 200, 202, 201 — the middle fragment arrives last.
	if nals, err := d.Push(buildRTP(200, []byte{fuIndicator, fuHeaderStart, 0x01})); err != nil || len(nals) != 0 {
		t.Fatalf("start: nals=%v err=%v", nals, err)
	}
	if nals, err := d.Push(buildRTP(202, []byte{fuIndicator, fuHeaderEnd, 0x03})); err == nil || len(nals) != 0 {
		t.Fatalf("out-of-order end: nals=%v err=%v, want an error and no NAL", nals, err)
	}
	// The delayed middle fragment finally shows up. However this is handled
	// internally, it must not retroactively complete anything and it must
	// not panic on a sequence number the assembler has already moved past.
	if nals, err := d.Push(buildRTP(201, []byte{fuIndicator, fuHeaderMid, 0x02})); err == nil || len(nals) != 0 {
		t.Fatalf("late middle: nals=%v err=%v, want an error and no NAL", nals, err)
	}
	if d.Emitted() != 0 {
		t.Errorf("Emitted() = %d, want 0 — nothing here was ever a genuine complete run", d.Emitted())
	}
	if d.Dropped() == 0 {
		t.Error("Dropped() = 0, want at least 1 — this run never completed intact")
	}
}

// ── general robustness: nothing here may panic ───────────────────────────────

func TestZeroLengthPayloadDoesNotPanic(t *testing.T) {
	pkt := buildRTP(1, nil)
	d := NewDepacketizer()
	nals, err := d.Push(pkt)
	if err == nil {
		t.Fatal("want an error for a zero-length RTP payload")
	}
	if len(nals) != 0 {
		t.Fatalf("got %d NALs from an empty payload, want 0", len(nals))
	}
}

func TestUnsupportedPacketizationTypeIsReportedNotPanicked(t *testing.T) {
	// Type 26 is MTAP16 — a real RFC 6184 packetization mode, just not one
	// this package implements (see h264.go's doc comment for why).
	payload := []byte{26, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
	d := NewDepacketizer()
	nals, err := d.Push(buildRTP(1, payload))
	if err == nil {
		t.Fatal("want an error naming the unsupported type, not a silent drop or a panic")
	}
	if len(nals) != 0 {
		t.Fatalf("got %d NALs, want 0", len(nals))
	}
}

func TestTruncatedRTPPacketDoesNotPanic(t *testing.T) {
	d := NewDepacketizer()
	for _, n := range []int{0, 1, 8, 11} {
		if _, err := d.Push(make([]byte, n)); err == nil {
			t.Errorf("a %d-byte packet (shorter than the 12-byte RTP header) was accepted", n)
		}
	}
}

// A malformed RTP header — a CSRC count or an extension length that runs past
// the packet — is exactly as wire-controlled and exactly as unbounded as a
// STAP-A size, and must be checked the same way: before it is used to slice,
// not after.
func TestRTPHeaderBoundsChecks(t *testing.T) {
	t.Run("CSRC count runs past the packet", func(t *testing.T) {
		pkt := make([]byte, 12)
		pkt[0] = 0x8F // version=2, CC=1111=15 (claims 15 CSRC words = 60 bytes)
		if _, _, err := parseRTPHeader(pkt); err == nil {
			t.Fatal("want an error, not a panic, for a CSRC count the packet cannot hold")
		}
	})
	t.Run("extension length runs past the packet", func(t *testing.T) {
		pkt := make([]byte, 16) // 12-byte header + 4-byte extension header, no data
		pkt[0] = 0x90           // version=2, X=1 (extension present), CC=0
		// Extension header: 2 bytes profile id (unused), 2 bytes length in
		// 32-bit WORDS. Claim 0xFFFF words — far more than exists.
		binary.BigEndian.PutUint16(pkt[14:16], 0xFFFF)
		if _, _, err := parseRTPHeader(pkt); err == nil {
			t.Fatal("want an error for an extension length the packet cannot hold")
		}
	})
	t.Run("padding count exceeds the payload", func(t *testing.T) {
		pkt := make([]byte, 13) // 12-byte header + 1 payload/padding byte
		pkt[0] = 0xA0           // version=2, P=1 (padding present), CC=0
		pkt[12] = 200           // claims 200 bytes of padding in a 1-byte payload
		if _, _, err := parseRTPHeader(pkt); err == nil {
			t.Fatal("want an error for a padding count larger than the payload")
		}
	})
	t.Run("wrong RTP version", func(t *testing.T) {
		pkt := make([]byte, 12)
		pkt[0] = 0x40 // version=1
		if _, _, err := parseRTPHeader(pkt); err == nil {
			t.Fatal("want an error for an RTP version this package does not speak")
		}
	})
}

// ── fuzzing: the properties an example-based test would not think to try ────
//
// The unit tests above check the malformed shapes someone thought of. A
// fuzzer, seeded with the same literal vectors, finds the STAP-A size and
// RTP-header-length combinations nobody wrote by hand — which is exactly
// where an unchecked wire-controlled length turns into a slice panic.

func FuzzDepacketizerPush(f *testing.F) {
	f.Add(buildRTP(1, []byte{0x67, 0x42, 0x00, 0x1e}))                                     // single NAL
	f.Add(buildRTP(2, []byte{0x18, 0x00, 0x02, 0x68, 0xCE, 0x00, 0x03, 0x65, 0x88, 0x84})) // STAP-A
	f.Add(buildRTP(10, []byte{0x5C, 0x85, 0xAA, 0xBB}))                                    // FU-A start
	f.Add(buildRTP(11, []byte{0x5C, 0x05, 0xCC, 0xDD}))                                    // FU-A middle
	f.Add(buildRTP(12, []byte{0x5C, 0x45, 0xEE}))                                          // FU-A end
	f.Add(buildRTP(3, []byte{0x18, 0x00, 0x05, 0xAA, 0xBB}))                               // truncated STAP-A
	f.Add([]byte{})
	f.Add(make([]byte, 11))
	f.Add(buildRTP(1, nil))

	f.Fuzz(func(t *testing.T, raw []byte) {
		d := NewDepacketizer()
		nals, err := d.Push(raw)
		if err != nil {
			return // refusing any single packet is always allowed
		}
		for _, nal := range nals {
			// Every emitted NAL must carry the Annex-B start code this
			// package promises, plus at least one header byte — a NAL
			// "unit" with nothing after the start code is not a unit.
			if len(nal) < 5 {
				t.Fatalf("emitted a %d-byte NAL, shorter than start-code+header", len(nal))
			}
			if !bytes.Equal(nal[:4], []byte{0, 0, 0, 1}) {
				t.Fatalf("emitted NAL % x does not begin with the Annex-B start code", nal)
			}
		}
	})
}

// FuzzDepacketizerSequence drives one Depacketizer with three packets in a
// row, which is what it takes to reach the cross-packet state — an FU-A
// reassembly left in progress across calls — that a single-packet fuzz
// target cannot touch.
func FuzzDepacketizerSequence(f *testing.F) {
	f.Add(
		buildRTP(10, []byte{0x5C, 0x85, 0xAA, 0xBB}),
		buildRTP(11, []byte{0x5C, 0x05, 0xCC, 0xDD}),
		buildRTP(12, []byte{0x5C, 0x45, 0xEE}),
	)
	f.Add(
		buildRTP(20, []byte{0x5C, 0x85, 0xAA}),
		buildRTP(22, []byte{0x5C, 0x45, 0xEE}), // gap
		buildRTP(23, []byte{0x67, 0x42}),       // single NAL after the gap
	)
	f.Add([]byte{}, []byte{}, []byte{})

	f.Fuzz(func(t *testing.T, a, b, c []byte) {
		d := NewDepacketizer()
		for _, pkt := range [][]byte{a, b, c} {
			nals, err := d.Push(pkt)
			if err != nil {
				continue
			}
			for _, nal := range nals {
				if len(nal) < 5 || !bytes.Equal(nal[:4], []byte{0, 0, 0, 1}) {
					t.Fatalf("malformed emitted NAL % x", nal)
				}
			}
		}
		// The counters are a running record, never a claim stronger than
		// what was actually seen: neither can be negative, and only NALs
		// this Depacketizer actually produced can be "emitted".
		if d.Emitted() < 0 || d.Dropped() < 0 {
			t.Fatalf("negative counters: emitted=%d dropped=%d", d.Emitted(), d.Dropped())
		}
	})
}
