package wire_test

// The report the controller signs must be the message the contract describes.
//
// proto/vectors/reports.json is generated by a JavaScript signer and verified by
// an independent JavaScript checker. Nothing connected either to the Go the
// controller actually runs. This does: it signs a report with the production
// path and requires the bytes to canonicalise the way the contract says, so a
// drift between the two shows up here rather than as `badsig` at a gate.

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"testing"

	"github.com/vul-os/aql/controller/internal/jcs"
	"github.com/vul-os/aql/controller/internal/wire"
)

func TestSignedReportMatchesTheContractShape(t *testing.T) {
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i + 1)
	}
	priv := ed25519.NewKeyFromSeed(seed)

	raw, err := wire.SignCtlReport(priv, "dev-1", "0.1.0", 1789000020, map[string]wire.ConfigEntry{
		"pulse_ms": {Value: 700, Source: wire.SourceDefault},
		"hold_max": {Value: 45, Source: wire.SourceConfig},
	})
	if err != nil {
		t.Fatal(err)
	}

	var got map[string]any
	if err := json.Unmarshal(raw, &got); err != nil {
		t.Fatal(err)
	}
	if got["typ"] != "ctl.report" || got["v"] != float64(0) {
		t.Fatalf("typ/v = %v/%v, want ctl.report/0", got["typ"], got["v"])
	}
	if got["device_id"] != "dev-1" || got["firmware"] != "0.1.0" {
		t.Errorf("device_id/firmware = %v/%v", got["device_id"], got["firmware"])
	}

	cfg, ok := got["config"].(map[string]any)
	if !ok {
		t.Fatalf("config is %T, want an object", got["config"])
	}
	hold, ok := cfg["hold_max"].(map[string]any)
	if !ok {
		t.Fatalf("config.hold_max is %T, want an object with value and source", cfg["hold_max"])
	}
	if hold["value"] != float64(45) || hold["source"] != "config" {
		t.Errorf("hold_max = %v, want {value:45 source:config}", hold)
	}

	// The signature must cover the message MINUS sig, canonicalised — the same
	// rule the hub applies. Verifying it here proves the controller's signer and
	// the contract agree, without either checking its own work.
	sig, _ := got["sig"].(string)
	if sig == "" {
		t.Fatal("the report carries no signature")
	}
	delete(got, "sig")
	canonical, err := jcs.Canonicalize(got)
	if err != nil {
		t.Fatal(err)
	}
	sigBytes, err := base64.RawURLEncoding.DecodeString(sig)
	if err != nil {
		t.Fatalf("signature is not base64url: %v", err)
	}
	if !ed25519.Verify(priv.Public().(ed25519.PublicKey), canonical, sigBytes) {
		t.Errorf(`the signature does not verify over JCS(message minus sig).

Canonical form was:
%s

A hub applying the contract's rule would reject every report this controller
sends, as badsig, with nothing to say why.`, canonical)
	}
}
