package httpapi

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"regexp"
	"testing"
)

// proto/vectors/webhooks.json — the OUTBOUND webhook profile, as data.
//
// webhookdispatch_test.go already proves the dispatcher's behaviour. What it
// cannot prove is that the format this hub emits is the format that was
// PUBLISHED for receivers to implement against, because both halves of that
// comparison live in this package: a test that recomputes the HMAC with
// signWebhook is only asserting signWebhook agrees with itself, and renaming
// X-Aql-Signature-256 to X-Hub-Sig would keep every one of those tests green
// while breaking every receiver in the field.
//
// So the expectations come from outside: a file generated by
// proto/vectors/generate.mjs, re-derived independently in JavaScript by
// proto/vectors/verify.mjs, and read here. Changing the wire format now
// requires changing the published vectors, which is the point — that is a
// deliberate act with a diff, not an incidental rename.
//
// It is also what makes the profile portable. proto/WEBHOOK-PROFILE.md is
// implementable from this file alone, without running a hub.

type webhookVectorFile struct {
	Profile map[string]any `json:"profile"`
	Vectors []struct {
		Name         string            `json:"name"`
		Secret       string            `json:"secret"`
		Event        string            `json:"event"`
		Body         string            `json:"body"`
		Preimage     string            `json:"preimage"`
		SignatureHex string            `json:"signature_hex"`
		Headers      map[string]string `json:"headers"`
	} `json:"vectors"`
}

func loadWebhookVectors(t *testing.T) webhookVectorFile {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	var path string
	for i := 0; i < 6; i++ {
		p := filepath.Join(dir, "proto", "vectors", "webhooks.json")
		if _, err := os.Stat(p); err == nil {
			path = p
			break
		}
		dir = filepath.Dir(dir)
	}
	if path == "" {
		t.Fatal("proto/vectors/webhooks.json not found walking up from the package directory")
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var f webhookVectorFile
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	// Coverage floor. A corpus-driven test whose corpus failed to load reports
	// PASS while checking nothing, which is the specific way gates in this
	// suite have been wrong before.
	if len(f.Vectors) < 6 {
		t.Fatalf("loaded %d vectors from %s; the file looks truncated (the corpus this gate was written against had 6)",
			len(f.Vectors), path)
	}
	return f
}

var hexSig = regexp.MustCompile(`^[0-9a-f]{64}$`)

// The signature rule itself, against externally-derived expectations.
func TestWebhookSignatureMatchesThePublishedVectors(t *testing.T) {
	f := loadWebhookVectors(t)
	checked := 0
	for _, v := range f.Vectors {
		t.Run(v.Name, func(t *testing.T) {
			ts := v.Headers[webhookTimestampHeader]
			if ts == "" {
				t.Fatalf("vector carries no %s header", webhookTimestampHeader)
			}
			// The preimage first, separately: when an implementation is wrong
			// it is almost always wrong here, and an HMAC mismatch alone gives
			// an implementer nothing to look at.
			if got := ts + "." + v.Body; got != v.Preimage {
				t.Fatalf("preimage disagrees with the vector\n got: %q\nwant: %q", got, v.Preimage)
			}
			got := signWebhook(v.Secret, ts, []byte(v.Body))
			if got != v.SignatureHex {
				t.Errorf("signWebhook does not reproduce the published signature\n got: %s\nwant: %s",
					got, v.SignatureHex)
			}
			if !hexSig.MatchString(got) {
				t.Errorf("signature %q is not 64 lowercase hex characters", got)
			}
		})
		checked++
	}
	if checked != len(f.Vectors) {
		t.Fatalf("ran %d of %d vectors", checked, len(f.Vectors))
	}
	t.Logf("reproduced %d published webhook signatures", checked)
}

// The header NAMES, which are as much of the contract as the algorithm and are
// the part a refactor can change without any other test noticing.
func TestWebhookHeaderNamesAreThePublishedOnes(t *testing.T) {
	f := loadWebhookVectors(t)
	for _, want := range []struct{ field, constant string }{
		{"signature_header", webhookSignatureHeader},
		{"timestamp_header", webhookTimestampHeader},
		{"event_header", webhookEventHeader},
	} {
		got, _ := f.Profile[want.field].(string)
		if got == "" {
			t.Fatalf("proto/vectors/webhooks.json profile has no %s", want.field)
		}
		if got != want.constant {
			t.Errorf("%s: the hub sends %q but the published profile says %q; "+
				"every receiver in the field implements the published name",
				want.field, want.constant, got)
		}
	}
	// And the same names on an actual vector, so the profile block cannot
	// agree with the constants while the corpus uses something else.
	for _, v := range f.Vectors {
		if v.Headers[webhookSignatureHeader] != v.SignatureHex {
			t.Errorf("%s: no %s header carrying signature_hex", v.Name, webhookSignatureHeader)
		}
		if v.Headers[webhookEventHeader] != v.Event {
			t.Errorf("%s: no %s header carrying the event name", v.Name, webhookEventHeader)
		}
	}
}

// The published event vocabulary must be one the hub will actually dispatch.
// A vector for an event knownWebhookEvent() rejects would document a delivery
// that can never happen.
func TestPublishedWebhookEventsAreDispatchable(t *testing.T) {
	f := loadWebhookVectors(t)
	seen := map[string]bool{}
	for _, v := range f.Vectors {
		if !knownWebhookEvent(v.Event) {
			t.Errorf("%s: the vectors publish event %q, which this hub would drop as unknown",
				v.Name, v.Event)
		}
		seen[v.Event] = true
	}
	// Both directions: every event the hub can send should have a vector, or
	// the profile documents half the surface.
	for _, e := range KnownWebhookEvents() {
		if !seen[e] {
			t.Errorf("event %q is dispatchable but has no published vector", e)
		}
	}
}

// End to end through the real request builder: the constants above could all
// agree and `attempt` could still set them on the wrong request. This asserts
// the bytes a receiver sees.
func TestARealDeliveryCarriesThePublishedHeaders(t *testing.T) {
	f := loadWebhookVectors(t)
	v := f.Vectors[0]

	var gotSig, gotTS, gotEvent, gotBody string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotSig = r.Header.Get(webhookSignatureHeader)
		gotTS = r.Header.Get(webhookTimestampHeader)
		gotEvent = r.Header.Get(webhookEventHeader)
		raw, _ := io.ReadAll(r.Body)
		gotBody = string(raw)
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	d := newWebhookDispatcher(nil, quietLogger())
	// deliverOne would need a store for the secret; attempt() is the unit that
	// builds the request, and it is where the SSRF re-check and the headers
	// live. webhookFor already sets AllowPrivate, which httptest's loopback
	// bind requires.
	if _, err := d.attempt(t.Context(), webhookFor(srv.URL), v.Event, []byte(v.Body), v.Secret); err != nil {
		t.Fatalf("delivery failed: %v", err)
	}
	if gotBody != v.Body {
		t.Errorf("body on the wire differs from the vector\n got: %q\nwant: %q", gotBody, v.Body)
	}
	if gotEvent != v.Event {
		t.Errorf("%s = %q, want %q", webhookEventHeader, gotEvent, v.Event)
	}
	if gotTS == "" {
		t.Fatalf("no %s header on the wire", webhookTimestampHeader)
	}
	// The timestamp is "now", so the signature cannot equal the vector's — but
	// it must be the vector's RULE applied to the timestamp actually sent.
	if want := signWebhook(v.Secret, gotTS, []byte(gotBody)); gotSig != want {
		t.Errorf("the signature on the wire is not HMAC(secret, ts+\".\"+body)\n got: %s\nwant: %s",
			gotSig, want)
	}
	if gotSig == "" || !hexSig.MatchString(gotSig) {
		t.Errorf("signature on the wire is not 64 lowercase hex characters: %q", gotSig)
	}
}
