-- =====================================================
-- Disable RLS on All Tables
-- Allows queries to work without RLS policies
-- =====================================================

ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE bots DISABLE ROW LEVEL SECURITY;
ALTER TABLE gardens DISABLE ROW LEVEL SECURITY;
ALTER TABLE pools DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_garden_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_pool_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_commands DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_telemetry DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_alerts DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE mowing_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE pool_cleaning_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE coverage_areas DISABLE ROW LEVEL SECURITY;
ALTER TABLE bot_pricing DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_fees DISABLE ROW LEVEL SECURITY;
ALTER TABLE organization_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs DISABLE ROW LEVEL SECURITY;

COMMENT ON SCHEMA public IS 'RLS disabled for all tables to allow unrestricted access';

